server {
    listen 443 ssl;
    server_name localhost;

    #SSL設定(ドメイン取得したら必要に応じて変更する)
    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    #リダイレクト設定
    #一時的なリダイレクトコード(302)にしているが、将来的には恒久的なリダイレクトコード(301)にしたい
    location = / {
        return 302 /matcha/;
    }
    location = /matcha {
        return 302 /matcha/;
    }

    #React用のエンドポイント(フロントエンドサーバー)
    location /matcha/ {
        proxy_pass http://react:5173;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    #Rust用のエンドポイント(Restfull APIサーバー)
    location /matcha-api/ {
        proxy_pass http://rust:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
