services:
  nginx:
    container_name: omatcha_nginx
    build:
      context: .
      dockerfile: docker/dockerfile.nginx
      args:
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
    ports:
      - "443:443"
    volumes:
      - ./workspace/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react
      - rust

  react:
    container_name: omatcha_react
    build:
      context: .
      dockerfile: docker/dockerfile.react
    environment:
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
      NEXT_ALLOWED_DEV_ORIGINS: ${NEXT_ALLOWED_DEV_ORIGINS:-}
    volumes:
      - ./workspace/react:/workspace
      - react_node_modules:/workspace/node_modules
      - react_next:/workspace/.next
    working_dir: /workspace
    command: sh -c "npm ci --no-audit --no-fund && npm run dev"

  rust:
    container_name: omatcha_rust
    build:
      context: .
      dockerfile: docker/dockerfile.rust
    environment:
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
    volumes:
      - ./workspace/rust:/workspace
    working_dir: /workspace
    command: cargo run
    depends_on:
      - db

  db:
    container_name: omatcha_db
    build:
      context: .
      dockerfile: docker/dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: omatcha
      MYSQL_USER: omatcha
      MYSQL_PASSWORD: omatcha_password
    ports:
      - "3306:3306"
    volumes:
      - ./service/db/db_data:/var/lib/mysql
      - ./workspace/db:/docker-entrypoint-initdb.d:ro
    command:
      - mysqld
      - --character-set-server=utf8mb4 #文字コードをUTF-8に設定
      - --collation-server=utf8mb4_0900_ai_ci #照合順序をUTF-8に設定

volumes:
  react_node_modules:
  react_next:
